### ISSUE TITLE
fails to parse metadata with issues_url set to null

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/puppet_metadata#31]
while reviewing  installed modules I run into the following error:
```
Checking /etc/puppetlabs/code/environments/choria/modules/mcollective_agent_iptables/metadata.json
/usr/lib/ruby/gems/3.0.0/gems/puppet_metadata-1.1.1/lib/puppet_metadata/metadata.rb:38:in `initialize': Invalid metadata: The property 'issues_url' of type null did not match the following type: string (PuppetMetadata::InvalidMetadataException)
	from /usr/lib/ruby/gems/3.0.0/gems/puppet_metadata-1.1.1/lib/puppet_metadata.rb:13:in `new'
	from /usr/lib/ruby/gems/3.0.0/gems/puppet_metadata-1.1.1/lib/puppet_metadata.rb:13:in `parse'
	from /usr/lib/ruby/gems/3.0.0/gems/puppet_metadata-1.1.1/lib/puppet_metadata.rb:20:in `read'
	from /usr/lib/ruby/gems/3.0.0/gems/metadata_json_deps-0.3.0/lib/metadata_json_deps.rb:21:in `block in run'
	from /usr/lib/ruby/gems/3.0.0/gems/metadata_json_deps-0.3.0/lib/metadata_json_deps.rb:19:in `each'
	from /usr/lib/ruby/gems/3.0.0/gems/metadata_json_deps-0.3.0/lib/metadata_json_deps.rb:19:in `run'
	from /usr/lib/ruby/gems/3.0.0/gems/metadata_json_deps-0.3.0/bin/metadata-json-deps:13:in `<top (required)>'
	from /usr/bin/metadata-json-deps:23:in `load'
	from /usr/bin/metadata-json-deps:23:in `<main>'
```

the json file:

```json
{
  "name": "choria-mcollective_agent_iptables",
  "version": "4.0.1",
  "author": "R.I.Pienaar <rip@devco.net>",
  "summary": "An agent that manipulates a specific single chain with iptables and ip6tables",
  "license": "ASL 2.0",
  "source": "http://projects.puppetlabs.com/projects/mcollective-plugins/wiki",
  "project_page": "http://projects.puppetlabs.com/projects/mcollective-plugins/wiki",
  "issues_url": null,
  "dependencies": [
    {
      "name": "choria/mcollective",
      "version_requirement": ">= 0.4.0 < 2.0.0"
    }
  ],
  "data_provider": null,
  "requirements": [
    {
      "name": "puppet",
      "version_requirement": ">= 4.9.0"
    }
  ]
}
```

**Comment by bastelfreak** [comment]
data is generated from https://github.com/choria-plugins/iptables-agent/blob/master/agent/iptables.ddl + https://github.com/choria-io/mcorpc-ruby-support/blob/df27d38e0fd0cf418c4689fa0a442736bb449939/lib/mcollective/pluginpackager/templates/forge/metadata.json.erb

**Comment by ekohl** [comment]
This comes from https://github.com/voxpupuli/metadata-json-lint. Have you tried to validate it directly?

**Comment by ekohl** [comment]
This should be an issue against metadata-json-lint. It specifies it must be a string:
https://github.com/voxpupuli/metadata-json-lint/blob/6919241c0fa0ad791b939fb23595ca7e5aee500b/lib/metadata-json-lint/schema.rb#L42-L45
